[build]
includeDir = "src"
outDir = "docs"

[docusaurus]
title = "Completionist Documentation"
tagline = "A Roblox game built with Rojo"
url = "https://kristianpetras.github.io"
baseUrl = "/completionist/"
organizationName = "kristianpetras"
projectName = "completionist"

[navbar]
title = "Completionist"

[[navbar.items]]
label = "API"
to = "api"

[[navbar.items]]
label = "GitHub"
href = "https://github.com/kristianpetras/completionist"
position = "right"

[footer]
style = "dark"
copyright = "Copyright © {year} Kristian Petras. Built with Moonwave."

[[footer.links]]
title = "Docs"

[[footer.links.items]]
label = "API Reference"
to = "api"

[[footer.links]]
title = "Community"

[[footer.links.items]]
label = "GitHub"
href = "https://github.com/kristianpetras/completionist"

[gitMetadata]
editUrl = "https://github.com/kristianpetras/completionist/edit/main/"