# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

# Moonwave cannot be installed on MacOS, please install it manually using npm or fix this.
# moonwave = "evaera/moonwave@1.2.0"

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
wally = "UpliftGames/wally@0.3.2"
lune = "lune-org/lune@0.8.9"
stylua = "JohnnyMorganz/StyLua@2.1.0"
selene = "Kampfkarren/selene@0.29.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.53.1"