[config]
# Standard library configuration for Roblox
std = "roblox+testez"

# File inclusion patterns
includes = ["src/**/*.lua", "src/**/*.luau", "tests/**/*.lua"]

# File exclusion patterns (add as needed)
excludes = []

# Rule severity configuration
# Options: "allow", "warn", "deny"
[rules]
# Core rules for code quality
unused_variable = "warn"
undefined_variable = "deny"
global_usage = "warn"
shadowing = "warn"
unbalanced_assignments = "deny"
unreachable_code = "warn"
type_check_inside_call = "warn"

# Roblox-specific rules
roblox_incorrect_color3_new_bounds = "deny"
roblox_incorrect_roact_usage = "warn"
roblox_suspicious_udim2_new = "warn"

# Style rules (can be adjusted based on team preferences)
almost_swapped = "warn"
compare_nan = "deny"
duplicate_keys = "deny"
empty_if = "warn"
if_same_then_else = "warn"
ifs_same_cond = "warn"
unscoped_variables = "warn"

# Performance-related rules
parenthese_conditions = "allow"
suspicious_reverse_loop = "warn"

# Allow some common patterns that might be flagged
incorrect_standard_library_use = "warn"
mixed_table = "allow"
