[package]
name = "kristian-petras/completionist"
# x-release-please-start-version
version = "1.3.0"
# x-release-please-end
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
signal = "sleitnick/signal@1.5.0"
comm = "sleitnick/comm@0.3.0"

[dev-dependencies]
