name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Rokit tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.rokit/bin
          ~/.rokit/tool-storage
        key: ${{ runner.os }}-rokit-${{ hashFiles('**/rokit.toml') }}
        restore-keys: |
          ${{ runner.os }}-rokit-

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.2

    - name: Install Rokit tools
      run: rokit install --no-trust-check

    - name: Cache Wally packages
      uses: actions/cache@v4
      with:
        path: |
          Packages/
          DevPackages/
        key: ${{ runner.os }}-wally-${{ hashFiles('**/wally.toml', '**/wally.lock') }}
        restore-keys: |
          ${{ runner.os }}-wally-

    - name: Install Wally packages
      run: wally install

    - name: Setup Python for pre-commit
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

    - name: Build project
      run: mkdir -p build && rojo build -o build/completionist.rbxlx

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: completionist
        path: build/completionist.rbxlx
