name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install npm dependencies
      run: npm ci
    
    - name: Setup Aftman
      uses: ok-nick/setup-aftman@v0.4.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install Aftman tools
      run: aftman install
      
    - name: Cache Rust tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-rust-tools-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-rust-tools-
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install StyLua and Selene
      run: |
        if ! command -v stylua &> /dev/null; then
          cargo install stylua
        fi
        if ! command -v selene &> /dev/null; then
          cargo install selene
        fi
        
    - name: Check formatting
      run: stylua --check src/
      
    - name: Run linting
      run: selene src/
       
    - name: Install Wally packages
      run: wally install
      
    - name: Build place file
      run: rojo build default.project.json -o completionist.rbxlx
      
    - name: Build test file
      run: rojo build test.project.json -o test.rbxlx
      
    - name: Validate test build
      run: |
        if [ ! -f test.rbxlx ]; then
          echo "❌ Test build failed - test.rbxlx not found"
          exit 1
        fi
        echo "✅ Test build successful - ready for manual execution in Roblox Studio"
      
    - name: Build documentation
      run: moonwave build
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: completionist-build
        path: completionist.rbxlx
        
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: completionist-tests
        path: test.rbxlx
        
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: completionist-docs
        path: docs/