name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-lint-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rokit tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.rokit/bin
          ~/.rokit/tool-storage
        key: ${{ runner.os }}-rokit-${{ hashFiles('**/rokit.toml') }}
        restore-keys: |
          ${{ runner.os }}-rokit-

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.2

    - name: Install Rokit tools
      run: rokit install

    - name: Check formatting
      run: stylua --check src/

    - name: Run linting
      run: selene src/

    - name: Cache Wally packages
      uses: actions/cache@v4
      with:
        path: |
          Packages/
          DevPackages/
        key: ${{ runner.os }}-wally-${{ hashFiles('**/wally.toml', '**/wally.lock') }}
        restore-keys: |
          ${{ runner.os }}-wally-

    - name: Install Wally packages
      run: wally install

    - name: Build place file
      run: rojo build default.project.json -o completionist.rbxlx

    - name: Run tests with Lune
      run: lune run tests/run-tests.luau

    - name: Build documentation
      run: moonwave build || echo "Moonwave build failed, using existing docs if available"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: completionist-build
        path: completionist.rbxlx

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: completionist-docs
        path: docs/
