name: CI/PR Checks

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# Cancel previous runs when new commits are pushed
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-and-build:
        name: Test, Lint & Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci --include=optional

            - name: Run security audit
              run: npm run audit

            - name: Run linting and formatting checks
              run: npm run check

            - name: Run TypeScript type check
              run: npm run typecheck

            - name: Run tests
              run: npm test
              
            - name: Run tests with coverage (PR only)
              if: github.event_name == 'pull_request'
              run: npm run test:ci

            - name: Build project and generate place file
              run: npm run build:place

            - name: Validate build output
              run: |
                  if [ ! -d "out" ]; then
                    echo "❌ Build output directory not found"
                    exit 1
                  fi
                  if [ ! -f "completionist.rbxl" ]; then
                    echo "❌ Place file not generated"
                    exit 1
                  fi
                  echo "✅ Build completed successfully"
                  echo "✅ Place file generated successfully ($(wc -c < completionist.rbxl) bytes)"

            # Upload artifacts only for PRs (for testing/review purposes)
            - name: Upload build artifacts (PR only)
              if: github.event_name == 'pull_request'
              uses: actions/upload-artifact@v4
              with:
                  name: completionist
                  path: completionist.rbxl
                  retention-days: 7