name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Selene
      run: |
        cargo install selene
        
    - name: Run Selene
      run: selene src/
      
    - name: Build with Rojo
      uses: ok-nick/setup-aftman@v0.4.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install Rojo
      run: aftman install
      
    - name: Build place file
      run: rojo build default.project.json -o completionist.rbxlx
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: completionist-build
        path: completionist.rbxlx