name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
        - uses: googleapis/release-please-action@v4
          id: release
          with:
            release-type: node
            token: ${{ secrets.GITHUB_TOKEN }}

  build-release-artifact:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      
      - name: Install dependencies
        run: npm ci --include=optional
      
      - name: Build place file
        run: npm run build:place
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: completionist
          path: completionist.rbxl
          retention-days: 1
      
      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} \
            completionist.rbxl \
            --clobber

  deploy-to-roblox:
    runs-on: ubuntu-latest
    needs: [release-please, build-release-artifact]
    if: ${{ needs.release-please.outputs.release_created }}
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: completionist
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
      
      - name: Install tools
        run: rokit install --no-trust-check
      
      - name: Deploy to Roblox (Production)
        run: mantle deploy --environment prod
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_OPEN_CLOUD_API_KEY: ${{ secrets.MANTLE_OPEN_CLOUD_API_KEY }}
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Commit updated mantle state
        run: |
          git add .mantle-state.yml
          if git diff --staged --quiet; then
            echo "✅ No mantle state changes to commit"
          else
            echo "📝 Committing mantle state changes from production deployment"
            git commit -m "chore: update mantle state after production deployment ${{ needs.release-please.outputs.tag_name }}

            - Updated production environment state
            - Deployment completed for release ${{ needs.release-please.outputs.tag_name }}
            - Auto-generated by GitHub Actions"
            git push origin main
            echo "✅ Mantle state committed and pushed successfully"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}